spring:
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    open-in-view: false
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: TRACE